apiVersion: v1
kind: Service
metadata:
  name: {{ include "fraud-detection-service.fullname" . }}
  labels:
    {{- include "fraud-detection-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "fraud-detection-service.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
