apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "card-service.fullname" . }}
  labels:
    {{- include "card-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "card-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "card-service.selectorLabels" . | nindent 8 }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              {{- if $v.secretKeyRef }}
              valueFrom:
                secretKeyRef:
                  name: {{ $v.secretKeyRef.name }}
                  key: {{ $v.secretKeyRef.key }}
              {{- else }}
              value: {{ $v | quote }}
              {{- end }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
