replicaCount: 2

image:
  repository: "{{ .Values.global.ecrRegistry }}/loan-service"
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8091

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8091
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8091
  initialDelaySeconds: 30
  periodSeconds: 5
  failureThreshold: 3

env:
  JWT_SECRET:
    secretKeyRef:
      name: banking-secrets
      key: jwt-secret
  DB_PASSWORD:
    secretKeyRef:
      name: banking-secrets
      key: db-password
  REDIS_HOST: redis-master.banking.svc.cluster.local
  KAFKA_BOOTSTRAP_SERVERS: banking-kafka.banking.svc.cluster.local:9092
  EUREKA_SERVER_URL: http://discovery-server.banking.svc.cluster.local:8761/eureka/

podDisruptionBudget:
  enabled: true
  minAvailable: 1

serviceAccount:
  create: true
  name: "loan-service-sa"

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/actuator/prometheus"
  prometheus.io/port: "8091"
